; Custom RX: ESP32-C3 SuperMini + Ebyte E80-900M2213S (LR1121)
; Monorepo env name: e80_esp32c3_rx

[env:e80_esp32c3_rx_via_UART]
extends = env_common_esp32c3rx, radio_LR1121
board = esp32-c3-devkitm-1
build_flags =
	${env_common_esp32c3rx.build_flags}
	${radio_LR1121.build_flags}
	-D TARGET_E80_ESP32C3_RX
	-D DEBUG_LOG
	-D DEV_USB_CRSF=1
monitor_speed = 460800
upload_speed = 921600

[env:e80_esp32c3_rx_via_WIFI]
extends = env:e80_esp32c3_rx_via_UART

[env:e80_esp32c3_rx_via_BetaflightPassthrough]
extends = env:e80_esp32c3_rx_via_UART

[env:e80_esp32c3_rx]
extends = env:e80_esp32c3_rx_via_UART
